services:
  aniseek-web:
    image: ghcr.io/elpitagoras14/aniseek-web:latest
    pull_policy: always
    container_name: aniseek-web
    restart: unless-stopped
    depends_on:
      aniseek-api:
        condition: service_healthy
    ports:
      - "3000:80"
    environment:
      - API_URL=${API_URL}
      - AUTH_ENABLED=${AUTH_ENABLED}

  aniseek-api:
    image: ghcr.io/elpitagoras14/aniseek-api:latest
    pull_policy: always
    container_name: aniseek-api
    init: true
    restart: unless-stopped
    depends_on:
      aniseek-db:
        condition: service_healthy
      aniseek-redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=prod
      - AUTH_ENABLED=${AUTH_ENABLED}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@aniseek-db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://aniseek-redis:6379
      - ANIMES_FOLDER=${ANIMES_FOLDER}
      - ACCESS_TOKEN_EXP_MIN=${ACCESS_TOKEN_EXP_MIN}
      - REFRESH_TOKEN_EXP_DAY=${REFRESH_TOKEN_EXP_DAY}
    volumes:
      - anime-data:${ANIMES_FOLDER}
    dns:
      - 8.8.8.8
      - 1.1.1.1

  aniseek-worker:
    image: ghcr.io/elpitagoras14/aniseek-worker:latest
    pull_policy: always
    container_name: aniseek-worker
    init: true
    restart: unless-stopped
    depends_on:
      aniseek-db:
        condition: service_healthy
      aniseek-redis:
        condition: service_healthy
    environment:
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@aniseek-db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://aniseek-redis:6379
      - ANIMES_FOLDER=${ANIMES_FOLDER}
      - MAX_DOWNLOAD_RETRIES=${MAX_DOWNLOAD_RETRIES}
      - RETRY_DOWNLOAD_INTERVAL=${RETRY_DOWNLOAD_INTERVAL}
      - DRAMATIQ_PROCESSES=${DRAMATIQ_PROCESSES}
      - DRAMATIQ_THREADS=${DRAMATIQ_THREADS}
      - dramatiq_queue_prefetch=${DRAMATIQ_THREADS}
      - BRAVE_PATH=/usr/bin/brave-browser
    volumes:
      - anime-data:${ANIMES_FOLDER}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    healthcheck:
      test: ["CMD", "pgrep", "-f", "dramatiq"]
      interval: 30s
      timeout: 10s
      retries: 3

  aniseek-db:
    image: postgres:18.1-alpine
    container_name: aniseek-db
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 5s

  aniseek-redis:
    image: redis:8.4.0-alpine
    container_name: aniseek-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  postgres-data:
  redis-data:
  anime-data:
