services:
  aniseek-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aniseek-web
    restart: unless-stopped
    depends_on:
      - aniseek-api
    ports:
      - 3000:80
    environment:
      - AUTH_ENABLED=false

  aniseek-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aniseek-api
    init: true
    restart: unless-stopped
    depends_on:
      aniseek-db:
        condition: service_healthy
      aniseek-redis:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      - AUTH_ENABLED=False
      - ADMIN_USER=admin
      - ADMIN_PASS=admin123
      - SECRET_KEY=secret
      - ALGORITHM=HS256
      - DB_URL=postgresql://postgres:postgres@aniseek-db:5432/postgres
      - REDIS_URL=redis://aniseek-redis:6379
      - ANIMES_FOLDER=/animes
      - ACCESS_TOKEN_EXP_MIN=60
      - REFRESH_TOKEN_EXP_DAY=10
    volumes:
      - animes-data:/animes
    dns:
      - 8.8.8.8
      - 1.1.1.1

  aniseek-worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: aniseek-worker
    init: true
    restart: unless-stopped
    depends_on:
      aniseek-db:
        condition: service_healthy
      aniseek-redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://aniseek-redis:6379
      - DB_URL=postgresql://postgres:postgres@aniseek-db:5432/postgres
      - ANIMES_FOLDER=/animes
      - MAX_DOWNLOAD_RETRIES=5
      - RETRY_DOWNLOAD_INTERVAL=15
      - DRAMATIQ_PROCESSES=2
      - DRAMATIQ_THREADS=4
      - dramatiq_queue_prefetch=4
      - BRAVE_PATH=/usr/bin/brave-browser
    volumes:
      - animes-data:/animes
    dns:
      - 8.8.8.8
      - 1.1.1.1

  aniseek-db:
    image: postgres:18.1-alpine
    container_name: aniseek-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  aniseek-redis:
    image: redis:8.4.0-alpine
    container_name: aniseek-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  animes-data:
